import random

BASE_DOMAINS = [
    "example.com",
    "test-site.org",
    "company.io",
    "webapp.dev",
    "corporate.net",
    "app.example.com",
    "api.test-site.org",
    "acme.corp",
]

INTERESTING_PATHS = [
    # Admin interfaces
    "/admin",
    "/administrator",
    "/wp-admin",
    "/dashboard",
    "/console",
    "/manage",
    "/management",
    "/control",
    "/panel",
    "/adm",
    # Authentication endpoints
    "/login",
    "/signin",
    "/signup",
    "/register",
    "/auth",
    "/oauth",
    "/oidc",
    "/password-reset",
    "/forgot-password",
    "/change-password",
    "/openid-configuration",
    # API endpoints
    "/api",
    "/api/v1",
    "/api/v2",
    "/graphql",
    "/rest",
    "/service",
    "/api/users",
    "/api/data",
    "/api/admin",
    "/api/config",
    "/goto",
    # File related
    "/download",
    "/upload",
    "/file",
    "/files",
    "/documents",
    "/attachments",
    "/imports",
    "/exports",
    "/backup",
    "/backups",
    # Database related
    "/sql",
    "/query",
    "/db",
    "/database",
    "/data",
    "/export",
    # Common vulnerable files
    "/config",
    "/settings",
    "/system",
    "/debug",
    "/test",
    "/dev",
    "/phpinfo.php",
    "/info.php",
    "/server-status",
    "/server-info",
    # Common vulnerable extensions
    "/index.php",
    "/admin.php",
    "/upload.php",
    "/config.php",
    "/old.php.bak",
    "/config.asp",
    "/login.jsp",
    "/admin.aspx",
    "/web.config",
    "/backup.zip",
    "/config.bak",
    "/redirect.php",
    "/report.pdf",
    "/archive.tar.gz",
    # Paths with sensitive information
    "/users",
    "/user",
    "/accounts",
    "/profile",
    "/profiles",
    "/members",
    "/customers",
    "/customer",
    "/orders",
    "/order",
    "/cart",
    "/checkout",
    "/execute",
    "/tools",
    # Internal services
    "/internal",
    "/private",
    "/staging",
    "/dev",
    "/test",
    "/beta",
    "/jenkins",
    "/jira",
    "/gitlab",
    "/kibana",
    "/grafana",
]

INTERESTING_PARAMS = [
    # Command injection
    "cmd",
    "exec",
    "command",
    "run",
    "system",
    "shell",
    "execute",
    "ping",
    # File operations
    "file",
    "path",
    "filename",
    "upload",
    "download",
    "document",
    "attachment",
    "include",
    "require",
    "import",
    "export",
    "load",
    "save",
    "open",
    "read",
    # Database
    "id",
    "user_id",
    "order_id",
    "item_id",
    "product_id",
    "category_id",
    "query",
    "sql",
    "filter",
    "where",
    "select",
    "delete",
    "update",
    "insert",
    # Authentication
    "username",
    "user",
    "pass",
    "password",
    "token",
    "auth",
    "key",
    "apikey",
    "session",
    "cookie",
    "jwt",
    "secret",
    "hash",
    "salt",
    # Application flow
    "redirect",
    "url",
    "callback",
    "next",
    "return",
    "target",
    "dest",
    "forward",
    "goto",
    "continue",
    "success",
    "error",
    "cancel",
    # Dangerous
    "debug",
    "test",
    "dev",
    "beta",
    "sandbox",
    "mock",
    "fake",
    "dummy",
    "admin",
    "root",
    "manage",
    "control",
    "grant",
    "revoke",
    "allow",
    "deny",
]

NORMAL_PATHS = [
    "/",
    "/home",
    "/about",
    "/contact",
    "/content",
    "/landing",
    "/images",
    "/docs",
    "/contact-us",
    "/products",
    "/services",
    "/blog",
    "/news",
    "/faq",
    "/articles",
    "/help",
    "/support",
    "/terms",
    "/privacy",
    "/sitemap",
    "/search",
    "/category",
    "/tag",
    "/page",
    "/post",
    "/article",
    "/resource",
    "/media",
    "/asset",
    "/static",
    "/css",
    "/js",
    "/img",
    "/images",
    "/fonts",
    "/icons",
]

NORMAL_PARAMS = [
    "page",
    "limit",
    "offset",
    "sort",
    "order",
    "filter",
    "q",
    "query",
    "search",
    "category",
    "tag",
    "type",
    "format",
    "view",
    "layout",
    "style",
    "theme",
    "lang",
    "locale",
    "currency",
    "country",
    "utm_source",
    "utm_medium",
    "utm_campaign",
    "ref",
    "source",
]

# Sample URL generation patterns for different security categories
pattern_categories = {
    "SSRF_REDIRECT": [
        lambda: f"{random.choice(BASE_DOMAINS)}/redirect?url=https://{random.choice(BASE_DOMAINS)}/profile",
        lambda: f"{random.choice(BASE_DOMAINS)}/login?back=//{random.choice(BASE_DOMAINS)}/admin",
        lambda: f"{random.choice(BASE_DOMAINS)}/auth?next=http%3A%2F%2Fevil.com",
        lambda: f"{random.choice(BASE_DOMAINS)}/goto?dest=https://partner-site.com/login",
        lambda: f"{random.choice(BASE_DOMAINS)}/oauth/authorize?redirect_uri=https://app.com/callback&state=xyz",
    ],
    "DANGEROUS_PARAMS": [
        lambda: f"{random.choice(BASE_DOMAINS)}/search?query=SELECT+*+FROM+users+ORDER+BY+username",
        lambda: f"{random.choice(BASE_DOMAINS)}/tools/ping?ip=127.0.0.1",
        lambda: f"{random.choice(BASE_DOMAINS)}/exec?cmd=ls+-la",
        lambda: f"{random.choice(BASE_DOMAINS)}/debug?command=pwd;id",
    ],
    "INTERESTING_FILES": [
        lambda: f"{random.choice(BASE_DOMAINS)}/download?file=../../../etc/shadow",
        lambda: f"{random.choice(BASE_DOMAINS)}/backup/db_backup_{random.randint(2020, 2024)}.sql.gz",
        lambda: f"{random.choice(BASE_DOMAINS)}/config/settings.yml",
        lambda: f"{random.choice(BASE_DOMAINS)}/.git/config",
        lambda: f"{random.choice(BASE_DOMAINS)}/files/report_{random.randint(1, 100)}.pdf",
        lambda: f"{random.choice(BASE_DOMAINS)}/export?format=json&data=users",
    ],
    "OAUTH_OIDC": [
        lambda: f"{random.choice(BASE_DOMAINS)}/connect/authorize?client_id=app&response_type=code"
        f"&scope=openid&state=abc",
        lambda: f"{random.choice(BASE_DOMAINS)}/.well-known/openid-configuration",
        lambda: f"{random.choice(BASE_DOMAINS)}/saml/sso?entityID=partner",
    ],
    "ADMIN_UNUSUAL_JS": [
        lambda: f"{random.choice(BASE_DOMAINS)}/admin/dashboard.js",
        lambda: f"{random.choice(BASE_DOMAINS)}/static/admin-utils-{random.randint(100, 999)}.js",
        lambda: f"{random.choice(BASE_DOMAINS)}/management/console",
        lambda: f"{random.choice(BASE_DOMAINS)}/secure/settings/panel",
        lambda: f"{random.choice(BASE_DOMAINS)}/internal/api/debug",
    ],
    "API": [
        lambda: f"{random.choice(BASE_DOMAINS)}/api/v2/users/{random.randint(1, 1000)}/orders",
        lambda: f"{random.choice(BASE_DOMAINS)}/rest/products?category=electronics",
        lambda: f"{random.choice(BASE_DOMAINS)}/graphql?query={{me{{id}}}}",
    ],
}
